# Numerical Python - Numpy
    - Array
    - [numbers]
    - Operations: Vectorized

In [2]:
list_a = list(range(1,100))
print(list_a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [4]:
squared=[]
for a in list_a:
    sq = a**2
    squared.append(sq)
print(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [7]:
print([a**2 for a in list_a])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [8]:
import numpy as np

In [9]:
arr1 = np.array(list_a)

In [10]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
arr1**2

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

In [12]:
arr1 = np.array([2,4,6,8])

In [13]:
arr1*2

array([ 4,  8, 12, 16])

# Array

#### Creating an array:

In [ ]:
# using a python list
arr1 = np.array([1,2,3,4,5,6,7,8,9,0])
arr1

In [ ]:
# using numpy arange
arr2 = np.arange(10)
arr2

In [18]:
arr3 = np.random.randn(1,10)

In [ ]:
arr4 = np.random.rand(1,10)

In [ ]:
arr1.dtype

In [ ]:
# all values
arr1.size

In [25]:
# rows and columns (more than 1d) or elements(1 dimension)
arr1.shape

(10,)

In [26]:
arr1.ndim

1

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[3,2,1],[6,5,4]])
arr2d

In [ ]:
arr2d.size

In [ ]:
arr2d.shape

In [ ]:
arr2d.ndim

In [37]:
arr2d = np.random.randn(5,4) # create an array of 5 rows and 4 columns with random numbers

In [38]:
arr3d = np.random.randn(3,4,5)# create an array of 4 rows and 5 columns and 3 copies with random numbers

In [39]:
arr3d = np.arange(64).reshape(4,4,4)

In [35]:
arr3d.ndim

3

In [36]:
arr3d.shape

(4, 4, 4)

In [40]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.ones((4,4))*15

array([[15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.]])

In [48]:
np.full((5,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Arithmetic with NumPy Arrays

In [50]:
arr2d1=np.arange(20).reshape(4,5)
arr2d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
arr2d2 = np.arange(20,40).reshape(4,5)
arr2d2

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [52]:
arr2d1 + arr2d2

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [53]:
arr2d1 * arr2d2

array([[  0,  21,  44,  69,  96],
       [125, 156, 189, 224, 261],
       [300, 341, 384, 429, 476],
       [525, 576, 629, 684, 741]])

In [54]:
arr2d1-100

array([[-100,  -99,  -98,  -97,  -96],
       [ -95,  -94,  -93,  -92,  -91],
       [ -90,  -89,  -88,  -87,  -86],
       [ -85,  -84,  -83,  -82,  -81]])

# Basic Indexing and Slicing

In [57]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [58]:
arr1[3]

4

In [59]:
arr1[-4]

7

In [60]:
arr1[3:6]

array([4, 5, 6])

In [61]:
arr2d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Slicing
### arr2d1[start_row:end_row , start_col:end_col]
# Idexing
## ar2d1[5, 2:5]

In [63]:
arr2d1[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [64]:
arr2d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
arr2d1[2,2:4]

array([12, 13])

In [66]:
arr2d1[2:3,2:4]

array([[12, 13]])

In [67]:
arr2d = np.arange(64).reshape(8,8)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [68]:
arr2d[4:7,3:7]

array([[35, 36, 37, 38],
       [43, 44, 45, 46],
       [51, 52, 53, 54]])

In [69]:
arr2d[4,:]

array([32, 33, 34, 35, 36, 37, 38, 39])

In [70]:
arr2d[4:5,:]

array([[32, 33, 34, 35, 36, 37, 38, 39]])

In [71]:
arr2d[:,5]

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [72]:
arr2d[:,5:6]

array([[ 5],
       [13],
       [21],
       [29],
       [37],
       [45],
       [53],
       [61]])

In [73]:
arr2d[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [74]:
arr2d[::-2]

array([[56, 57, 58, 59, 60, 61, 62, 63],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [76]:
arr2d[5,4]

44

In [77]:
arr2d[5:6,4:5]

array([[44]])

In [84]:
a = np.array([[[[[[[[[[[[[[[100]]]]]]]]]]]]]]])
a.ndim

15

# Boolean Indexing

In [85]:
arr = np.array(range(20))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [90]:
arr[arr%5==0]

array([ 0,  5, 10, 15])

In [91]:
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [92]:
arr[(arr>5) & (arr<15)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
or and 
|   &